### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by DmAg77** [oleg84/yuliayakovenko.ru#1]
Здравствуйте, Олег!

Видел ваши вопросы автору по реализации RNDIS на STM32, в частности вопросы по реализации на HAL. Удалось ли вам их решить?
Я только закончил проект на HAL CDC+MSC, подошла очередь RNDIS.

Прошу связаться со мной, если вопрос для Вас актуален.
e-mail: agapov.77@mail.ru 
e-mail: dm.agapov.77@gmail.com

P.S.: Не нашел другого способа написать Вам сообщение, поэтому пишу в "yuliayakovenko.ru".

**Comment by oleg84** [comment]
Отвечу по почте.
